const translations = {
  fr: {
    // Header, Navigation, Langues
    "header.title": "Zaroui Khaoula - Graphic designer -",
    "header.logo": "",
    "lang.fr": "Fr",
    "lang.en": "En",

    // Menu
    "menu.home": "Accueil",
    "menu.about": "A propos",
    "menu.projects": "Projets",
    "menu.gallery": "Galerie",
    "menu.blog": "Blog",
    "menu.contact": "Contact",

    // Accueil/Intro
    "intro.title": "Bienvenue dans le monde de design !",

    // About Section
    "about.title": "A propos",
    "about.subtitle": "<i class=\"fa fa-pencil\"></i> <em>Designer polyvalente, entre créativité & technique !</em>",
    "desc-1": "Créative, curieuse et passionnée, j'ai débuté mon parcours en design graphique en suivant des formations spécialisées et des programmes certifiés.",
    "desc-2": "Mon approche combine l'apprentissage structuré avec une sensibilité visuelle naturelle, m'amenant à explorer diverses ressources pour enrichir ma pratique.",
    "desc-3": "Mon désir d'approfondir mes connaissances m'a naturellement conduite vers des plateformes d'apprentissage de référence.",
    "desc-4": "Alors, j'ai entamé avec une formation dans les bases de web avec <mark>OpenClassrooms</mark>, en participant à des cours à libre accéss. Où j'ai acquis les compétences fondamentales en web général, HTML et CSS.",
    "desc-5": "En parallèle, j'ai poursuit mes études tant que self-taught avec des tutoriels Youtube et des projets fictifs pour me familiariser avec la création de formulaires et l'animation CSS.",
    "desc-6": "A la suite, j'ai complété une certification de 300 heures en Responsive Web Design sur <mark>freeCodeCamp</mark>, ce qui m'a permis de maîtriser l'intégration responsive et les bonnes pratiques du développement front-end moderne.",
    "desc-7": "Toujours à l'affût des innovations, j'intègre également l'intelligence artificielle dans mes processus de création.",
    "desc-8": "J'utilise des outils comme Cursor AI pour optimiser l'écriture de code, automatiser certaines backend tâches et tester plus rapidement mes idées, rendant mes projets plus fluides et performants.",
    "desc-9": "Deux plus, j'utilise <mark>Gamma</mark> pour réaliser des présentations pertinentes, et <mark>Chatgpt</mark> pour la raisonnement et le brainstorming.",
    "desc-10": "J'ai ainsi suivi la spécialisation UI/UX Design de <mark>CalArts</mark> sur Coursera, une formation complète qui m'a initiée aux méthodologies de design centrées utilisateur, à la création de maquettes web et mobiles, aux wireframes, et à la réflexion stratégique derrière une bonne expérience utilisateur.",
    "desc-11": "Pour valider mes compétences et solidifier mes connaissances en domaine de web et graphique, Je m'inscris à un BTS en multimédia et marketing.",
    "desc-12": "Maintenant, je suis en train de préparer les bases de mon studio en ligne de conception graphique et web, nommé \"<em>graphiroots_studio</em>\". Et je suis une nouvelle formation avec freecodecamp en Anglais destinés aux developpeurs.",

    // Compétences/Skills
    "skills.title": "Compétences",
    "skill-1": "Design graphique",
    "desc-skill-1": "Conception de logo",
    "desc-logo-2": "Logo mot-symbole",
    "desc-logo-1": "Logo pictogramme ou abstrait",
    "desc-logo-3": "Logo monogramme ou lettermark",
    "desc-logo-4": "Logo combiné",
    "desc-skill-2": "Identité visuelle",
    "desc-skill-2a": "Logotype et ses supports",
    "desc-skill-2b": "Palette de couleurs",
    "desc-skill-2c": "Typographie",
    "desc-skill-2d": "Éléments graphiques : motif, icônes, formes",
    "skill-3": "Designs pour les réseaux sociaux",
    "desc-skill-3a": "Template de publication",
    "desc-skill-3b": "Bannière de couverture",
    "skill-4": "Conception des imprimés (flyers, papier entête, cartes de visite...)",
    "tech-1": "Technologies : Adobe Illustrator, Adobe Photoshop, Canva",
    "hr-1": "",
    "skill-5": "Développement web",
    "tech-2": "Création de sites web responsives, intégration HTML/CSS, développement front-end",
    "desc-skill-5": "Création de formulaires interactifs",
    "desc-skill-3": "Site web vitrine responsive",
    "desc-skill-5b": "Site web portfolio avec formulaire validé des deux côtés",
    "tech-2b": "Technologies : HTML, CSS, JavaScript, Bootstrap",
    "hr-2": "",
    "skill-6": "UI/UX Design",
    "desc-skill-6": "Conception d'interfaces utilisateur, expérience utilisateur, wireframing",
    "tech-3": "Technologies : Figma, Adobe XD",
    "hr-3": "",
    "skill-7": "Motion graphique",
    "tech-4": "Technologies : Microsoft ClipChamp, Adobe After Effects, Adobe Premiere Pro",

    // Certifications
    "cert.title": "🥇 Certifications",
    "cert.uiux.title": "UI/UX Design Certification",
    "cert.uiux.id": "Identifiant de la certification : ",
    "cert.uiux.btn": "Voir la certification",
    "cert.uiux.date": "Date de délivrance : févr. 2024",
    "cert.responsive.title": "Responsive web site Certification",
    "cert.responsive.btn": "Voir la certification",
    "cert.responsive.date": "Date de délivrance : déc. 2023",

    // Projets
    "projects-title": "Projets",
    "projects.desc": "Découvrez une sélection de mes réalisations en design et développement web.",
    "projects.logo.title": "Conception de logos",
    "projects.logo.btn": "Voir le projet",
    "projects.social.title": "Réseaux sociaux",
    "projects.social.btn": "Voir le projet",
    "projects.print.title": "Les imprimées",
    "projects.print.btn": "Voir le projet",
    "projects.webdev.title": "Développement web",
    "projects.webdev.btn": "Voir le projet",
    "projects.webconcept.title": "Conception web",
    "projects.webconcept.btn": "Voir le projet",
    "projects.motion.title": "Motion Graphique",
    "projects.motion.btn": "Voir le projet",

    // Contact & Formulaire
    "contact-title": "Contact",
    "contact-desc": "Vous avez un projet graphique ou web ? Contactez-moi par 👇",
    "contact.email": "zarouikhaoula94@gmail.com",
    "contact.whatsapp": "",
    "contact.orform": "Ou via le formulaire ci-dessous :",
    "form.honeypot.label": "Ne pas remplir ce champ :",
    "form-name": "Nom",
    "form-subject": "Sujet",
    "form-message": "Message",
    "form-option-1": "Choisissez un sujet",
    "form-option-2": "Demande de logo",
    "form-option-3": "Demande d'identité visuelle",
    "form-option-4": "Demande de conception de maquette Web",
    "form-option-5": "Demande de site Web (landing page/site vitrine/portfolio)",
    "form-option-6": "Autre service",
    "form-privacy": "J'accepte que mes données soient utilisées pour me recontacter",
    "form-submit": "Envoyer",
    "form.submit.text": "Envoyer le message",
    "form.submit.loading": "<i class=\"fa fa-spinner fa-spin\"></i> Envoi en cours...",
    "form-success": "Votre message a été envoyé avec succès !",
    "form-error": "Une erreur est survenue. Veuillez réessayer.",
    "form.name.input": "",
    "form.name.error": "",
    "form.email.input": "",
    "form.email.error": "",
    "form.subject.input": "",
    "form.subject.error": "",
    "form.message.input": "",
    "form.message.counter": "0/1000 caractères",
    "form.message.error": "",
    "form.privacy.input": "",
    "form.privacy.error": "",
    "form.messages": "",

    // Divers
    "backtotop.btn": "",
    "footer.logo": "",
    "footer.name": "Zaroui Khaoula",
    "footer-desc": "<b>- Votre partenaire créatif !</b>-",
    "link-title1": "Liens utiles",
    "link-title2": "Suivez-moi",
    "footer.copy": "© 2025 Zaroui Khaoula - Tous droits réservés",
    "footer.linkedin": "",
    "footer.github": "",
    "footer.behance": "",
    "footer.instagram": "",
    "footer.facebook": ""
  },

  en: {
    // Header, Navigation, Langues
    "header.title": "Zaroui Khaoula - Graphic Designer -",
    "header.logo": "",
    "lang.fr": "Fr",
    "lang.en": "En",

    // Menu
    "menu.home": "Home",
    "menu.about": "About",
    "menu.projects": "Projects",
    "menu.gallery": "Gallery",
    "menu.blog": "Blog",
    "menu.contact": "Contact",

    // Accueil/Intro
    "intro.title": "Welcome to the world of design!",

    // About Section
    "about.title": "About",
    "about.subtitle": "<i class=\"fa fa-pencil\"></i> <em>Versatile designer, between creativity & technique!</em>",
    "desc-1": "Creative, curious and passionate, I started my graphic design journey through specialized training and certified programs.",
    "desc-2": "My approach combines structured learning with a natural visual sensitivity, leading me to explore various resources to enrich my practice.",
    "desc-3": "My desire to deepen my knowledge naturally led me to reference learning platforms.",
    "desc-4": "So, I started with a foundation in web basics at <mark>OpenClassrooms</mark>, participating in open-access courses. There, I acquired fundamental skills in general web, HTML, and CSS.",
    "desc-5": "At the same time, I continued my self-taught studies with YouTube tutorials and fictional projects to get familiar with form creation and CSS animation.",
    "desc-6": "Next, I completed a 300-hour Responsive Web Design certification at <mark>freeCodeCamp</mark>, which enabled me to master responsive integration and modern front-end development best practices.",
    "desc-7": "Always on the lookout for innovation, I also integrate artificial intelligence into my creative processes.",
    "desc-8": "I use tools like Cursor AI to optimize code writing, automate some backend tasks, and test ideas more quickly, making my projects smoother and more efficient.",
    "desc-9": "Additionally, I use <mark>Gamma</mark> to make relevant presentations, and <mark>Chatgpt</mark> for reasoning and brainstorming.",
    "desc-10": "I also completed the UI/UX Design specialization from <mark>CalArts</mark> on Coursera, a comprehensive course that introduced me to user-centered design methodologies, web and mobile mockup creation, wireframes, and the strategic thinking behind a good user experience.",
    "desc-11": "To validate and solidify my web and graphic skills, I enrolled in a multimedia and marketing BTS.",
    "desc-12": "Now, I am preparing the foundations for my online graphic and web design studio, named \"<em>graphiroots_studio</em>\". And I am following a new course with freecodecamp in English aimed at developers.",

    // Skills
    "skills.title": "Skills",
    "skill-1": "Graphic Design",
    "desc-skill-1": "Logo design",
    "desc-logo-2": "Wordmark logo",
    "desc-logo-1": "Pictogram or abstract logo",
    "desc-logo-3": "Monogram or lettermark logo",
    "desc-logo-4": "Combined logo",
    "desc-skill-2": "Visual identity",
    "desc-skill-2a": "Logotype and its supports",
    "desc-skill-2b": "Color palette",
    "desc-skill-2c": "Typography",
    "desc-skill-2d": "Graphic elements: pattern, icons, shapes",
    "skill-3": "Social media designs",
    "desc-skill-3a": "Post template",
    "desc-skill-3b": "Cover banner",
    "skill-4": "Print design (flyers, letterheads, business cards...)",
    "tech-1": "Technologies: Adobe Illustrator, Adobe Photoshop, Canva",
    "hr-1": "",
    "skill-5": "Web development",
    "tech-2": "Creation of responsive websites, HTML/CSS integration, front-end development",
    "desc-skill-5": "Creation of interactive forms",
    "desc-skill-3": "Responsive showcase website",
    "desc-skill-5b": "Portfolio website with two-way validated form",
    "tech-2b": "Technologies: HTML, CSS, JavaScript, Bootstrap",
    "hr-2": "",
    "skill-6": "UI/UX Design",
    "desc-skill-6": "UI design, user experience, wireframing",
    "tech-3": "Technologies: Figma, Adobe XD",
    "hr-3": "",
    "skill-7": "Motion design",
    "tech-4": "Technologies: Microsoft ClipChamp, Adobe After Effects, Adobe Premiere Pro",

    // Certifications
    "cert.title": "🥇 Certifications",
    "cert.uiux.title": "UI/UX Design Certification",
    "cert.uiux.id": "Certification ID: ",
    "cert.uiux.btn": "See certificate",
    "cert.uiux.date": "Date of issue: Feb. 2024",
    "cert.responsive.title": "Responsive web site Certification",
    "cert.responsive.btn": "See certificate",
    "cert.responsive.date": "Date of issue: Dec. 2023",

    // Projects
    "projects-title": "Projects",
    "projects.desc": "Discover a selection of my achievements in design and web development.",
    "projects.logo.title": "Logo design",
    "projects.logo.btn": "See project",
    "projects.social.title": "Social media",
    "projects.social.btn": "See project",
    "projects.print.title": "Prints",
    "projects.print.btn": "See project",
    "projects.webdev.title": "Web development",
    "projects.webdev.btn": "See project",
    "projects.webconcept.title": "Web conception",
    "projects.webconcept.btn": "See project",
    "projects.motion.title": "Motion design",
    "projects.motion.btn": "See project",

    // Contact & Form
    "contact-title": "Contact",
    "contact-desc": "Do you have a graphic or web project? Contact me 👇",
    "contact.email": "zarouikhaoula94@gmail.com",
    "contact.whatsapp": "",
    "contact.orform": "Or via the form below:",
    "form.honeypot.label": "Do not fill in this field:",
    "form-name": "Name",
    "form-subject": "Subject",
    "form-message": "Message",
    "form-option-1": "Choose a subject",
    "form-option-2": "Logo request",
    "form-option-3": "Visual identity request",
    "form-option-4": "Mockup design request",
    "form-option-5": "Website request (landing page/showcase/portfolio)",
    "form-option-6": "Other service",
    "form-privacy": "I agree that my data will be used to contact me",
    "form-submit": "Send",
    "form.submit.text": "Send message",
    "form.submit.loading": "<i class=\"fa fa-spinner fa-spin\"></i> Sending...",
    "form-success": "Your message has been sent successfully!",
    "form-error": "An error occurred. Please try again.",
    "form.name.input": "",
    "form.name.error": "",
    "form.email.input": "",
    "form.email.error": "",
    "form.subject.input": "",
    "form.subject.error": "",
    "form.message.input": "",
    "form.message.counter": "0/1000 characters",
    "form.message.error": "",
    "form.privacy.input": "",
    "form.privacy.error": "",
    "form.messages": "",

    // Divers
    "backtotop.btn": "",
    "footer.logo": "",
    "footer.name": "Zaroui Khaoula",
    "footer-desc": "<b>- Your creative partner!</b>-",
    "link-title1": "Useful links",
    "link-title2": "Follow me",
    "footer.copy": "© 2025 Zaroui Khaoula. All rights reserved.",
    "footer.linkedin": "",
    "footer.github": "",
    "footer.behance": "",
    "footer.instagram": "",
    "footer.facebook": ""
  }
};

function changeLanguage(lang) {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
}